### PR TITLE
fix error/death during gm.identify() on bad file

### LINKED ISSUE #68: Non-image files in image ingestion folder breaks ingestion process
Problem: In the ingestion folder (i.e. /nas) the presence of a file such as 'scoutbot.log' or a previously rejected image such as 'eland.jpg.error' throws an error and ingestion stops:

```
/usr/src/app/node_modules/gm/lib/command.js:318
          err = new Error('Command failed: ' + stderr);
                ^

Error: Command failed: gm identify: Unable to open file (/nas/scoutbot.log) [No such file or directory].
gm identify: Request did not return an image.

    at ChildProcess.onExit (/usr/src/app/node_modules/gm/lib/command.js:318:17)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  signal: null
}
```

Expected behaviour: non-image files get skipped and moved to an "errors" subdirectory (not in the hidden `.scout-hidden` folder), and message appears for administrator indicating that errors were found during processing.

### PR DESCRIPTION
**Pull request by naknomum**
claims to fix #68 and #73 by capturing failure of `gm.identify()` gracefully.

### CODE REVIEW

**Comment by TanyaStere42** [comment]
@simbamangu are you free to test this one?

**Comment by simbamangu** [comment]
Just tested with a small set of files, copying these to the /nas target (these are available in the MWS drive, root, as test_20240220T214550.7z):

Real JPGs, with different extensions / case because I think "JPEG" (with "E") might not be accepted:

- DSC_0006.JPG
- DSC_0007.JPEG
- DSC_0008.jpeg

Empty and text-only files:

- test_set_b_empty.jpg
- test_set_b_empty.png
- test_set_b_text.txt

Results:

1. One correctly generated error file: test_set_b_empty.jpg.error
2. DSC_0006.JPG disappears, apparently correctly ingested.
4. Crash in scout (`docker run`) terminal, see below.
5. Other files untouched.


```
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "src" argument must be of type string or an instance of Buffer or URL. Received type boolean (false)
    at Object.copyFile (node:internal/fs/promises:444:9)
    at workers.imageIngestion (/usr/src/app/app.js:352:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by simbamangu** [comment]
Update: adding the files one by one I can confirm that the empty PNG / JPG and text files are all correctly dealt with (rename to *.error, ignored otherwise) and the JPEG and jpeg extensions are what causes the problem.

**Comment by naknomum** [comment]
> Update: adding the files one by one I can confirm that the empty PNG / JPG and text files are all correctly dealt with (rename to *.error, ignored otherwise) and the JPEG and jpeg extensions are what causes the problem.

thanks for the testing. i will address this asap today.

**Comment by naknomum** [comment]
@simbamangu , @TanyaStere42 - should be fixed now to allow `.jpeg`/`.JPEG` extension now as well.

**Comment by simbamangu** [comment]
@TanyaStere42 passes the tests now.

**Review by simbamangu — APPROVED** [review]

**Review by TanyaStere42 — APPROVED** [review]
Testing done by @simbamangu , passed! Code looks good to me

**Pull request merged**
