### PR TITLE
60 filter image by datetime

### LINKED ISSUE #60: Create New Task - Filter Images by datetime
## Context
Users have discovered that there is a need for separating flight by the time of the flight, as well as the date

## User Story
As a lab lead creating new tasks, I am able to leverage a datetime filter that works off the image exif
- Page impacted: `main/views/pages/tasks-new.ejs`
- update 'startDate' and 'endDate' components to be some form of datetime input

## Technical Notes
Recommended to use `bootstrap-datetimepicker.js` (will need to use `moment.js` to get it working)

## QA verification
1. upload a series of images with known sequential datetime exif
1. navigate to create new task: select images modal

- [ ] start time is a datetime field
- [ ] end time is a datetime field
- [ ] filter respects datetime exif

### PR DESCRIPTION
**Pull request by erinz2020**
update startdate and enddate component to enable filter images by both date and time.

PR fixes #60 

Notes:
couldn't do a very detailed test on filtering by exact time because all exifTampStamp in my dev is 0 and changes to db will lose after docker restart

### CODE REVIEW

**Comment by TanyaStere42** [comment]
@naknomum can you test this? I also have no timestamp info

**Review by TanyaStere42 — APPROVED** [review]
code looks good, default behavior is great for no-timestamp filtering

**Comment by naknomum** [comment]
> @naknomum can you test this? I also have no timestamp info

yes, will test this branch with some date-stamped images today.

**Comment by erinz2020** [comment]
@TanyaStere42 now scout on QA has datetime data to test this pr, I tested and it was good, if you want to have a look you can test with 2024-12-03 15:23 and 2024-12-03 15:25, different image counts will be returned

**Pull request merged**
